# Publish to PyPi package index

name: PIP Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: 📦 Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/inventree-rexel-plugin
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies for building
        run: pip install --upgrade wheel setuptools twine build

      - name: Build Python package
        run: python3 -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
